base/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',  views.getRoutes),
    path('rooms/', views.getRooms),
    path('rooms/<str:pk>/', views.getRoom),
]

base/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),


    path('', views.home, name="home"),
    path('room/<str:pk>/', views.room, name="room"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    

    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),
    
    path('update-user/', views.updateUser, name="update-user"),
    
    
    path('topics/', views.topicsPage, name="topics"),
    path('activity/', views.activityPage, name="activity"),
     
    path('follow-user/<str:pk>/', views.follow_user, name="follow-user"),
    path('unfollow-user/<str:pk>/', views.unfollow_user, name="unfollow-user"),
    path('follower_list/', views.follower_list, name='follower_list'),
    path('follower_list/<int:pk>/', views.follower_list, name='follower_list'),
    
    path('inbox/', views.inbox, name="inbox"),
    path('message/<str:pk>/', views.viewMessage, name="message"),
    path('create-message/<str:pk>/', views.createMessage, name="create-message"),
    path('upvote/', views.upvote, name='upvote'),
    path('room/<int:pk>/access_code/', views.access_code, name='access_code'),
    
    path('room/<int:room_id>/kick-out/<int:user_id>/', views.kick_out_user, name='kick-out-user'),
    path('room/<int:room_id>/make-admin/<int:user_id>/', views.make_user_admin, name='make-user-admin'),
    path('room/<int:room_id>/un-admin/<int:user_id>/', views.unadmin_user, name='unadmin-user'),

    path('get_notifications/', views.get_notifications, name='get_notifications'),
    path('delete_notification/<int:notification_id>/', views.delete_notification, name='delete_notification'),
    path('delete_message/<int:message_id>/', views.delete_message, name='delete_message'),
    
    path('room/<int:room_pk>/invite/<int:user_pk>/', views.invite_to_room, name='invite_to_room'),
    path('join-room/<int:room_pk>/', views.join_room, name='join_room'),
    path('add_reaction/', views.add_reaction, name='add_reaction'),
    
    path('leaderboard/', views.leaderboard, name='leaderboard'),
]

uniBud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('api/', include('base.api.urls')),
    path('chatbot/', include('chatbot.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



# Create  models.

class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)
    bio = models.TextField(null=True)

    avatar = models.ImageField(null=True, default="avatar.svg")
    
    followers = models.ManyToManyField('self', related_name='following', blank=True, symmetrical=False)
    follower_count = models.IntegerField(default=0)
    last_checked = models.DateTimeField(auto_now_add=True)
    
    badges = models.ManyToManyField('base.Badge', blank=True)
    


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []



class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name



class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='created_rooms')
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(
        User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    upvotes = models.IntegerField(default=0)
    upvoted_by = models.ManyToManyField(User, related_name='upvoted_rooms')
    is_private = models.BooleanField(default=False)
    access_code = models.CharField(max_length=10, blank=True, null=True)
    admins = models.ManyToManyField(User, related_name="admin_rooms", blank=True)


    class Meta:
        ordering = ['-updated', '-created']


    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['is_read', '-created']

    def __str__(self):
        return self.body[0:50]
    

class UserRoomVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    voted_at = models.DateTimeField(auto_now_add=True)


class Notification(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    notification_type = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.sender} - {self.notification_type}"
    
    
class Reaction(models.Model):
    emoji = models.CharField(max_length=10)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.ForeignKey(Message, on_delete=models.CASCADE)



class Badge(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    icon = models.ImageField(upload_to='badges/')
    criteria = models.CharField(max_length=255)

    def __str__(self):
        return self.name

base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room
from .serializers import RoomSerializer
from base.api import serializers


@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms/:id'
    ]
    return Response(routes)


@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getRoom(request, pk):
    room = Room.objects.get(id=pk)
    serializer = RoomSerializer(room, many=False)
    return Response(serializer.data)

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Count, Sum
from django.contrib.auth import authenticate, login, logout
from .models import Room, Topic, Message, User, UserRoomVote, Notification, Reaction
from .forms import RoomForm, UserForm, MyUserCreationForm, MessageForm, UpvoteForm
from django.shortcuts import get_object_or_404
from django.utils import timezone
from .utils import assign_badges


# Create your views here.

def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Username OR password does not exit')

    context = {'page': page}
    return render(request, 'base/login_register.html', context)


def logoutUser(request):
    logout(request)
    return redirect('home')


def registerPage(request):
    form = MyUserCreationForm()

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'An error occurred during registration')

    return render(request, 'base/login_register.html', {'form': form})



def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    ).order_by('-upvotes')

    topics = Topic.objects.all()[0:5]
    room_count = rooms.count()
    top_host = User.objects.annotate(num_followers=Count('followers')).order_by('-num_followers')[:5]

    if request.user.is_authenticated:
        following_users = request.user.followers.all()
        room_messages = Message.objects.filter(
            Q(room__topic__name__icontains=q),
            Q(user=request.user) | Q(user__in=following_users)
        ).order_by('-created')[:5]
    else:
        room_messages = Message.objects.none()  # Return an empty queryset

    context = {'rooms': rooms, 'topics': topics, 
               'room_count': room_count, 'room_messages': room_messages,
               'top_host': top_host}
    return render(request, 'base/home.html', context)



def access_code(request, pk):
    room = Room.objects.get(id=pk)
    if request.method == 'POST':
        access_code = request.POST.get('access_code')
        if room.access_code == access_code:
            room.participants.add(request.user)  
            return redirect('room', pk=room.id)
        else:
            return render(request, 'base/access_code.html', {'room': room, 'error': 'Invalid access code'})
    else:
        return render(request, 'base/access_code.html', {'room': room})







@login_required(login_url='login')
def room(request, pk):
    room = Room.objects.get(id=pk)
    

    if room.is_private and request.user not in room.participants.all():
        return redirect('access_code', pk=room.id)

    room_messages = room.message_set.all().order_by('created')
    participants = room.participants.all()
    is_admin = request.user in room.admins.all()
    following = request.user.following.all()
    assign_badges(request.user)
    

    if request.method == 'POST':
        message = Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get('body')
        )
        room.participants.add(request.user)
        return redirect('room', pk=room.id)

    context = {'room': room, 'room_messages': room_messages,
               'participants': participants, 'is_admin': is_admin, 'following': following}
    return render(request, 'base/room.html', context)



@login_required(login_url='login')
def userProfile(request, pk):
    user = User.objects.get(id=pk)
    rooms = user.created_rooms.all()
    room_messages = user.message_set.all()
    topics = Topic.objects.all()
    followers_count = user.followers.all().count()
    is_following = user.followers.filter(id=request.user.id).exists()
    assign_badges(user)

    if request.method == 'POST':
        if 'follow' in request.POST:
            user.followers.add(request.user)
            user.follower_count += 1
            user.save()
            messages.success(request, 'You are now following ' + user.name)
            is_following = True

        elif 'unfollow' in request.POST:
            user.followers.remove(request.user)
            user.follower_count -= 1
            user.save()
            messages.success(request, 'You are no longer following ' + user.name)
            is_following = False

    context = {'user': user, 'rooms': rooms,
               'room_messages': room_messages, 'topics': topics,
               'followers_count': followers_count, 'is_following': is_following}
    return render(request, 'base/profile.html', context)

    


def leaderboard(request):
    users = User.objects.annotate(
        badge_count=Count('badges'),
        total_upvotes=Sum('created_rooms__upvotes')
    ).order_by('-badge_count', '-total_upvotes')
    context = {'users': users}
    return render(request, 'base/leaderboard.html', context)







@login_required(login_url='login')
def createRoom(request):
    form = RoomForm()
    topics = Topic.objects.all()
    assign_badges(request.user)
    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)

        Room.objects.create(
            host=request.user,
            topic=topic,
            name=request.POST.get('name'),
            description=request.POST.get('description'),
            is_private=request.POST.get('is_private') == 'on',
            access_code=request.POST.get('access_code'),
        )
        return redirect('home')

    context = {'form': form, 'topics': topics}
    return render(request, 'base/room_form.html', context)




@login_required(login_url='login')
def updateRoom(request, pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)
    topics = Topic.objects.all()
    assign_badges(request.user)
    if request.user != room.host:
        return HttpResponse('Your are not allowed here!!')

    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room.name = request.POST.get('name')
        room.topic = topic
        room.description = request.POST.get('description')
        room.is_private = request.POST.get('is_private') == 'on'
        new_access_code = request.POST.get('access_code')
        if room.is_private and new_access_code != room.access_code:
            room.access_code = new_access_code
        room.save()
        return redirect('home')

    context = {'form': form, 'topics': topics, 'room': room}
    return render(request, 'base/room_form.html', context)


     

@login_required
def deleteRoom(request, pk):
    room = Room.objects.get(id=pk)
    if request.method == 'POST':
        room.delete()
        return redirect('home')
    return render(request, 'base/delete.html', {'obj': room})


@login_required(login_url='login')
def deleteMessage(request, pk):
    message = Message.objects.get(id=pk)

    if request.user != message.user:
        return HttpResponse('You are not allowed here!')

    if request.method == 'POST':
        room_id = message.room.id
        message.delete()
        return redirect('room', pk=room_id)
    return render(request, 'base/delete.html', {'obj': message})




@login_required(login_url='login')
def updateUser(request):
    user = request.user
    form = UserForm(instance=user)

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('user-profile', pk=user.id)

    return render(request, 'base/update-user.html', {'form': form})





def topicsPage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    topics = Topic.objects.filter(name__icontains=q)
    return render(request, 'base/topics.html', {'topics': topics})

def activityPage(request):
    room_messages = Message.objects.all()
    return render(request, 'base/activity.html', {'room_messages': room_messages})


def followers(request, pk):
    user = get_object_or_404(User, pk=pk)
    followers_count = user.followers.count()
    context = {'user': user, 'followers_count': followers_count}
    return render(request, 'profile.html', context)



def follow_user(request, pk):
    user_to_follow = get_object_or_404(User, pk=pk)
    if request.user.is_authenticated:
        request.user.following.add(user_to_follow)
        user_to_follow.follower_count = user_to_follow.followers.all().count()
        user_to_follow.save()
        notification = Notification(sender=request.user, receiver=user_to_follow, notification_type='follow')
        notification.save()
    return redirect('user-profile', pk=pk)

def unfollow_user(request, pk):
    user_to_unfollow = get_object_or_404(User, pk=pk)
    if request.user.is_authenticated:
        request.user.following.remove(user_to_unfollow)
        user_to_unfollow.follower_count = user_to_unfollow.followers.all().count()

base/templates/base/access_code.html
<!-- base/access_code.html -->
{% extends 'main.html' %}

{% block content %}
<main class="access-code layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{{request.META.HTTP_REFERER}}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.960h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"></path>
                        </svg>
                    </a>
                    <h3>Enter Access Code</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" method="post">
                    {% csrf_token %}
                    <div class="form__group">
                        <label for="access_code">Enter access code for room "{{ room.name }}":</label>
                        <input type="text" name="access_code" required>
                    </div>
                    <div class="form__action">
                        <a class="btn btn--dark" href="{{request.META.HTTP_REFERER}}">Cancel</a>
                        <button class="btn btn--main" type="submit">Join Room</button>
                    </div>
                    {% if error %}
                        <p>{{ error }}</p>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

  

base/templates/base/activity_component.html
 <div class="activities">
        <div class="activities__header">
            <h2>Recent Activities</h2>
        </div>
      
        {% for message in room_messages %}
        <div class="activities__box">
            <div class="activities__boxHeader roomListRoom__header">
                <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
                    <div class="avatar avatar--small">
                        <img src="{{message.user.avatar.url}}" />
                    </div>
                    <p>
                        @{{message.user.username}}
                        <span>{{message.created|timesince}} ago</span>
                    </p>
                </a>
      
                {% if request.user == message.user %}
                <div class="roomListRoom__actions">
                    <a href="{% url 'delete-message' message.id %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                            <title>remove</title>
                            <path
                                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                            </path>
                        </svg>
                    </a>
                </div>
                {% endif %}
      
            </div>
            <div class="activities__boxContent">
                <p>replied to post “<a href="{% url 'room' message.room.id %}">{{message.room}}</a>”</p>
                <div class="activities__boxRoomContent">{{message.body}}</div>
            </div>
        </div>
        {% endfor %}
      

 

    </div>
  

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}
<main class="delete-item layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{{request.META.HTTP_REFERER}}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Back</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" method="POST" action="">
                    {% csrf_token %}
                    <div class="form__group">
                        <p>Are you sure you want to delete "{{obj}}"?</p>
                    </div>

                    <div class="for__group">
                        <input class="btn btn--main" type="submit" value="Confirm" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

base/templates/base/delete_old.html
{% extends 'main.html' %}


{% block content %}


<form method="POST" action="">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{obj}}"?</p>
    
    <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
    <input type="submit" value="Confirm"/>

</form>







{% endblock content %}

base/templates/base/feed_component.html
{% for room in rooms %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
        {% if room.host %}
        <a href="{% url 'user-profile' room.host.id %}" class="roomListRoom__author">
    {% else %}
        
    {% endif %}
            <div class="avatar avatar--small">
                <img src="{{room.host.avatar.url}}" />
            </div>
            <span>Host @{{room.host.username}}</span>
        </a>
        <div class="roomListRoom__actions">
            <span>{{room.created|timesince}} ago</span>
            <form class="upvote-form" method="POST" action="{% url 'upvote' %}">
                {% csrf_token %}
                <input type="hidden" name="room" value="{{ room.id }}">
                <div class="upvote-container" style="cursor: pointer;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-up" viewBox="0 0 16 16"> <path fill-rule="evenodd" d="M8 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L7.5 2.707V14.5a.5.5 0 0 0 .5.5z"/> 
                    </svg>
                    <span class="upvote-count">{{ room.upvotes }}</span>
                </div>
            </form>
        </div>
    </div>
    <div class="roomListRoom__content">
        <a href="{% url 'room' room.id %}">{{room.name}}</a>
    </div>
    <div class="roomListRoom__meta">
        <a href="{% url 'room' room.id %}" class="roomListRoom__joined">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>user-group</title>
                <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
                </path>
                <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
                </path>
                <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
                </path>
                <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
                </path>
            </svg>
            {{room.participants.all.count}} Joined
        </a>
        <p class="roomListRoom__topic">{{room.topic.name}}</p>
        {% if room.is_private %}
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-lock" viewBox="0 0 16 16">
            <path d="M7.293 1.5a1 1 0 0 1 1.414 0L11 3.793V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v3.293l2.354 2.353a.5.5 0 0 1-.708.708L8 2.207l-5 5V13.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 1 0 1h-4A1.5 1.5 0 0 1 2 13.5V8.207l-.646.647a.5.5 0 1 1-.708-.708L7.293 1.5Z"/>
            <path d="M10 13a1 1 0 0 1 1-1v-1a2 2 0 0 1 4 0v1a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-4a1 1 0 0 1-1-1v-2Zm3-3a1 1 0 0 0-1 1v1h2v-1a1 1 0 0 0-1-1Z"/>
          </svg>
        {% endif %}
    </div>
</div>

    
    
    
{% endfor %}

base/templates/base/topics.html
{% extends 'main.html' %}

{% block content %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Browse Topics</h3>
        </div>
      </div>

      <div class="topics-page layout__body">
        <form action="" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
              </path>
            </svg>
            <input name="q" placeholder="Search for topics" />
          </label>
        </form>

        <ul class="topics__list">
          <li>
            <a href="{% url 'topics' %}" class="active">All <span>{{topics.count}}</span></a>
          </li>
          {% for topic in topics %}
          <li>
            <a href="{% url 'home' %}?q={{topic.name}}">{{ topic.name }} <span>{{topic.room_set.all.count}}</span></a>
          </li>
          {% endfor %}

        </ul>
      </div>
    </div>
  </div>
</main>

{% endblock content %}

base/templates/base/topics_component.html
<div class="topics">
  <div class="topics__header">
      <h2>Browse Topics</h2>
  </div>
  <ul class="topics__list">
      <li>
          <a href="{% url 'home' %}" class="active">All <span>{{topics.count}}</span></a>
      </li>
      {% for topic in topics %}
      <li>
          <a href="{% url 'home' %}?q={{topic.name}}">{{topic.name}}<span>{{topic.room_set.all.count}}</span></a>
      </li>
      {% endfor %}

  </ul>
  <a class="btn btn--link" href="{% url 'topics' %}">
      More
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>chevron-down</title>
          <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
      </svg>
  </a>
</div>